# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b19d0d566512267717915416ed76026f7256b41447d2e60db6a1d12d0a49ae1fd89c9b466481d56df57ccb7ac18f7ff5c670633b46e0cbb220ddaa1981c691a8

test:
  secret_key_base: c9ccf947c2398c4d803521f3bb41dcc290347cb0d18cca7cd386ae8dd8f0bb2c954339bee879b8ab1f0686593a6c0803ed5b241b5382c17b3c9ff3f7c8e15f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
